### ISSUE TITLE
可以对模型调用层进行抽象，后续可以接入更多的模型

### ISSUE THREAD

**Issue by HildaM** [huangPengL/ChatGPT-Java-FunAi#13]
看了一下原代码，目前的功能都是强依赖于OpenAI的接口。如果后续想要接入Claude、chatGLM、chatRWKV、讯飞星火等模型，修改难度太大了。
建议将模型层抽象一下，这样后续可以很方便地引入更多gpt模型接口

**Comment by PenglongHuang** [comment]
感谢建议！
