### ISSUE TITLE
插入Pinecone向量库失败

### ISSUE THREAD

**Issue by 1463360815** [huangPengL/ChatGPT-Java-FunAi#2]
你好，我在尝试使用Pinecone时调用接口出现Remote host terminated the handshake错误
在网上查阅之后加上System.setProperty("https.protocols", "TLSv1,TLSv1.1,TLSv1.2")也不太行；
请问怎么解决呢
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/66824807/236787874-ec78c96d-6036-4dde-adbb-95a197da276f.png">

**Comment by xing-wei-zeng** [comment]
你的PINECONE_API_URL好像有误，https://docs.pinecone.io/reference/describe_index_stats_post 参考这个链接右侧的BASE_URL
