### ISSUE TITLE
上传PDF文档卡住

### ISSUE THREAD

**Issue by panyy** [huangPengL/ChatGPT-Java-FunAi#7]
![微信截图_20230529115023](https://github.com/huangPengL/ChatGPT-Java-FunAi/assets/5070279/eb784b76-29d4-46f4-9c38-5f1bba1f3989)

**Comment by huangPengL** [comment]
我们偷懒做的假的进度条hhh~单文件需要等待10s左右，多文件（5个文件）上传需要1分多钟

**Comment by huangPengL** [comment]
> ![微信截图_20230529115023](https://user-images.githubusercontent.com/5070279/241651703-eb784b76-29d4-46f4-9c38-5f1bba1f3989.png)

你好，这个问题确实存在。我们重新配置了nginx，导致部分设置没有跟上业务。目前已解决这个问题！
