### ISSUE TITLE
希望智能阅读也可以支持markdown格式

### ISSUE THREAD

**Issue by LiBaoxuan-Neil** [huangPengL/ChatGPT-Java-FunAi#8]

**Comment by huangPengL** [comment]
前端已经支持啦！有可能是gpt那边没有markdown格式返回结果。
![image](https://github.com/huangPengL/ChatGPT-Java-FunAi/assets/26277039/7f57ee30-7dd5-4f29-a388-0b12d4071543)

**Comment by LiBaoxuan-Neil** [comment]
希望未来智能阅读也能够上传markdown格式的文件
