### ISSUE TITLE
响应速度太快了

### ISSUE THREAD

**Issue by linweikeng** [huangPengL/ChatGPT-Java-FunAi#9]
大佬，我去访问了你们做的网站，聊天是秒回，我在openai官网聊天都没这么快，请问是怎么做到的

**Comment by huangPengL** [comment]
我猜也许是刚好随机到5美刀的apikey🤨
不过，技术上我们有做一些优化，比如：历史聊天记录从缓存中加载；流式输出用sse实现

**Comment by starplatinum3** [comment]
sse我调不通/(ㄒoㄒ)/~~
